server:
  port: 8761
spring:
  application:
    name: registry-server

---
# Discovery Server Access
#eureka:
#  instance:
#    hostname: localhost
#    leaseRenewalIntervalInSeconds: 5
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      healthcheck:
#        enabled: true
#    registryFetchIntervalSeconds: 5
#  server:
#      waitTimeInMsWhenSyncEmpty: 0
#      enable-self-preservation: false
#      eviction-interval-timer-in-ms: 4000

