# HTTP Server
server:
#  context-path: /users
  port: 8080   # HTTP (Tomcat) port

# Spring properties
spring:
  application:
     name: user-service
  cloud:
    services:
      registrationMethod: route

---
spring:
  profiles: dev

---
security:
  basic:
    enabled: false
---

# Logging
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

---
# Discovery Server Access
eureka:
#  instance:
#    hostname: localhost
#    leaseRenewalIntervalInSeconds: 5
#    lease-expiration-duration-in-seconds: 10
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
#      healthcheck:
#        enabled: true
#    registryFetchIntervalSeconds: 5
#  server:
#      waitTimeInMsWhenSyncEmpty: 0

# Endpoint setup
#endpoints:
#  restart:
#    enabled: true